==16403== 32 bytes in 1 blocks are definitely lost in loss record 33 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x143465: C_A_T_C_H_T_E_S_T_14() (arvore.cpp:307)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 34 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x143750: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:318)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 35 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:352)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 36 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:352)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 37 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:352)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 38 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:352)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 39 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:367)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 40 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:367)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403== 
==16403== 32 bytes in 1 blocks are definitely lost in loss record 41 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:367)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403== 
==16403== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 42 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1427FF: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:265)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 43 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x142B40: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:276)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 44 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x142E81: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:287)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 45 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1431C2: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:298)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 46 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x143750: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:318)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 128 (32 direct, 96 indirect) bytes in 1 blocks are definitely lost in loss record 47 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x17B1A2: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:113)
==16403==    by 0x17B1F6: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:119)
==16403==    by 0x17B1CC: Abb<int>* arv_busca<int>(Abb<int>*, int) (arvore.cpp:117)
==16403==    by 0x16AB85: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:367)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403== 
==16403== 192 (32 direct, 160 indirect) bytes in 1 blocks are definitely lost in loss record 48 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:352)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 49 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x143AF6: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:330)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
==16403== 288 (32 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 50 of 50
==16403==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16403==    by 0x17B14C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:85)
==16403==    by 0x16AB72: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:155)
==16403==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==16403==    by 0x143EAF: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:341)
==16403==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16403==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16403==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16403==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16403==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16403==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16403==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16403== 
