==16136== Invalid read of size 8
==16136==    at 0x16AABE: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:228)
==16136==    by 0x1445DB: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:405)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16136==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==16136==    by 0x16A4D2: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==16136==    by 0x141F58: main (catch.hpp:17543)
==16136==  Address 0x4df9160 is 16 bytes inside a block of size 32 free'd
==16136==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==16136==    by 0x16AAB9: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:226)
==16136==    by 0x1445DB: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:405)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16136==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==16136==    by 0x16A4D2: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==16136==  Block was alloc'd at
==16136==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16136==    by 0x17B1C6: Abb<int>* abb_inicia<int>(int) (arvore.cpp:152)
==16136==    by 0x16AB9B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==16136==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:171)
==16136==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:404)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16136== 
==16136== Invalid read of size 8
==16136==    at 0x16AABE: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:228)
==16136==    by 0x14461A: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:408)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16136==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==16136==    by 0x16A4D2: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==16136==    by 0x141F58: main (catch.hpp:17543)
==16136==  Address 0x4df91c0 is 16 bytes inside a block of size 32 free'd
==16136==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==16136==    by 0x16AAB9: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:226)
==16136==    by 0x14461A: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:408)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==16136==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==16136==    by 0x16A4D2: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==16136==  Block was alloc'd at
==16136==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16136==    by 0x17B1C6: Abb<int>* abb_inicia<int>(int) (arvore.cpp:152)
==16136==    by 0x16AB9B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==16136==    by 0x16ABC0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:182)
==16136==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:171)
==16136==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:404)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136== 
==16136== 32 bytes in 1 blocks are definitely lost in loss record 1 of 1
==16136==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16136==    by 0x17B1C6: Abb<int>* abb_inicia<int>(int) (arvore.cpp:152)
==16136==    by 0x16AB9B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==16136==    by 0x16ABDF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:183)
==16136==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:171)
==16136==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:404)
==16136==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16136==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16136==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16136==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16136==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16136==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16136== 
