==1360231== 32 bytes in 1 blocks are definitely lost in loss record 17 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x143449: C_A_T_C_H_T_E_S_T_14() (arvore.cpp:332)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360231==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 18 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x143734: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:343)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 19 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:377)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 20 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:377)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 21 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:377)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 22 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:392)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360231==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 23 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:392)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231== 
==1360231== 32 bytes in 1 blocks are definitely lost in loss record 24 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:392)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231== 
==1360231== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 28 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:392)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360231== 
==1360231== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 29 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:392)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231== 
==1360231== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 30 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:355)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231== 
==1360231== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 31 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:377)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360231==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==1360231== 
==1360231== 288 (32 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 32 of 32
==1360231==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360231==    by 0x17B351: Abb<int>* abb_inicia<int>(int) (arvore.cpp:118)
==1360231==    by 0x16AC37: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:148)
==1360231==    by 0x16AC5C: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==1360231==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:152)
==1360231==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:137)
==1360231==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:366)
==1360231==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360231==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360231==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360231==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360231==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360231== 
