==15428== 32 bytes in 1 blocks are definitely lost in loss record 7 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1427E3: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:297)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 8 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1427E3: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:297)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 9 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142B24: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:308)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 10 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142B24: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:308)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 11 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:319)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 12 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:319)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 13 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:319)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 14 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:319)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 15 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:330)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 16 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:330)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 17 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:330)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 18 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:330)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 19 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x143749: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:351)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 20 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x143749: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:351)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 21 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 22 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 23 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 24 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 25 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 26 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 27 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 28 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 29 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 30 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:373)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 31 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 32 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 33 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 34 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B262: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:131)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 35 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 36 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B291: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:133)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 37 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 38 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16AC5A: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:170)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 39 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 40 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 41 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 42 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 43 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x14424D: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 44 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x14424D: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 45 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x14424D: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 46 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x14424D: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 47 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x144262: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:386)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 48 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x144262: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:386)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 49 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x144262: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:386)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 50 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x144262: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:386)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 51 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 52 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B302: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:142)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 53 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 54 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B316: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:144)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 55 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 56 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16ABD1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:160)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 57 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 58 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:388)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 59 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x16AAC4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:213)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x16AAA9: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:210)
==15428==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 60 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DC9: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x1445E9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 61 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189DD7: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==15428==    by 0x17B235: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:128)
==15428==    by 0x16AB6C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:234)
==15428==    by 0x1445E9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
==15428== 32 bytes in 1 blocks are definitely lost in loss record 62 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x16AAC4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:213)
==15428==    by 0x16AB45: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:227)
==15428==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:404)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==15428== 
==15428== 64 bytes in 2 blocks are definitely lost in loss record 63 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E27: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 64 bytes in 2 blocks are definitely lost in loss record 64 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x189E35: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==15428==    by 0x17B2C0: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:139)
==15428==    by 0x16ACD5: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:180)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:362)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428== 
==15428== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 65 of 65
==15428==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==15428==    by 0x17B339: Abb<int>* abb_inicia<int>(int) (arvore.cpp:81)
==15428==    by 0x16AB9F: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:156)
==15428==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==15428==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:384)
==15428==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==15428==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==15428==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==15428==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==15428==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==15428==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==15428==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==15428== 
