==3167796== Invalid read of size 4
==3167796==    at 0x17B15F: int att_altura<int>(Abb<int>*) (arvore.cpp:132)
==3167796==    by 0x16AB4F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:229)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfe0f8 is 24 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 4
==3167796==    at 0x194203: int abb_altura<int>(Abb<int>*) (arvore.cpp:31)
==3167796==    by 0x189D65: int abb_get_fb<int>(Abb<int>*) (arvore.cpp:39)
==3167796==    by 0x17B1F8: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:106)
==3167796==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:231)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Address 0x4dfe0f8 is 24 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16AA64: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:203)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==    by 0x141F58: main (catch.hpp:17543)
==3167796==  Address 0x4dfe0f0 is 16 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 4
==3167796==    at 0x16AA7F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:205)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==    by 0x141F58: main (catch.hpp:17543)
==3167796==  Address 0x4dfe0e0 is 0 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid write of size 4
==3167796==    at 0x16AA8E: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:206)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==    by 0x141F58: main (catch.hpp:17543)
==3167796==  Address 0x4dfe0e0 is 0 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 4
==3167796==    at 0x16A9FF: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:196)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfe0e0 is 0 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16AA0E: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:197)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfe0e8 is 8 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16AA1B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:197)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfe0f0 is 16 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16A67E: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AA2F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:198)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==  Address 0x4dfe0e8 is 8 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16A68E: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AA2F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:198)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==  Address 0x4dfe0f0 is 16 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid free() / delete / delete[] / realloc()
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16AA2F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:198)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445D4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Address 0x4dfe0e0 is 0 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A689: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== Invalid read of size 4
==3167796==    at 0x17B1A8: int att_altura<int>(Abb<int>*) (arvore.cpp:139)
==3167796==    by 0x16AB4F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:229)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==  Address 0x4dfdf78 is 24 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== Invalid read of size 4
==3167796==    at 0x16A9FF: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:196)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144628: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==  Address 0x4dfdf60 is 0 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16AA0E: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:197)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144628: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==  Address 0x4dfdf68 is 8 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16AA1B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:197)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144628: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==    by 0x16A4B6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==3167796==  Address 0x4dfdf70 is 16 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16A67E: void abb_destroi<int>(Abb<int>*) (arvore.cpp:251)
==3167796==    by 0x16AA2F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:198)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144628: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfdf68 is 8 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== Invalid read of size 8
==3167796==    at 0x16A68E: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AA2F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:198)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144628: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796==  Address 0x4dfdf70 is 16 bytes inside a block of size 32 free'd
==3167796==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==3167796==    by 0x16A6AA: void abb_destroi<int>(Abb<int>*) (arvore.cpp:253)
==3167796==    by 0x16A699: void abb_destroi<int>(Abb<int>*) (arvore.cpp:252)
==3167796==    by 0x16AAF6: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:215)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==  Block was alloc'd at
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:396)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 17 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1427E3: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:294)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 18 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1427E3: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:294)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 19 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142B24: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:305)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 20 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142B24: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:305)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 21 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B2C5: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:121)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:316)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 22 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B2C5: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:121)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:316)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 23 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B2D9: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:122)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:316)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 24 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B2D9: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:122)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:316)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 25 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:327)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 26 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:327)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 27 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:327)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 28 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:327)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 29 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:231)
==3167796==    by 0x143749: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:348)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 30 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:231)
==3167796==    by 0x143749: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:348)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 31 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 32 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 33 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 34 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 35 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 36 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 37 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 38 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 39 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 40 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 41 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 42 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 43 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 44 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B253: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:112)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 45 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 46 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B267: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:113)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 47 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B2C5: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:121)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 48 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B2C5: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:121)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 49 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B2D9: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:122)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 50 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B2D9: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:122)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x14428C: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:385)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 51 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AABF: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:210)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x16AAA4: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:207)
==3167796==    by 0x1445BF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 52 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:231)
==3167796==    by 0x1445E9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 53 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:231)
==3167796==    by 0x1445E9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 32 bytes in 1 blocks are definitely lost in loss record 54 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AABF: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:210)
==3167796==    by 0x16AB3B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:224)
==3167796==    by 0x144613: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 57 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:359)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 58 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:359)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 59 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E0B: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:44)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:359)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 60 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189E19: Abb<int>* abb_esq_rotate<int>(Abb<int>*) (arvore.cpp:45)
==3167796==    by 0x17B296: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:119)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:359)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 61 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D87: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:62)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 64 bytes in 2 blocks are definitely lost in loss record 62 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x189D95: Abb<int>* abb_dir_rotate<int>(Abb<int>*) (arvore.cpp:63)
==3167796==    by 0x17B226: Abb<int>* go_fb<int>(Abb<int>*) (arvore.cpp:110)
==3167796==    by 0x16ACCB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:177)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
==3167796== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 63 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16AC64: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:169)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:359)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796== 
==3167796== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 64 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:381)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167796==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==3167796== 
==3167796== 288 (32 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 65 of 65
==3167796==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167796==    by 0x16ABDB: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:159)
==3167796==    by 0x16AC50: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:167)
==3167796==    by 0x16ABC7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:157)
==3167796==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:99)
==3167796==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:370)
==3167796==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167796==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167796==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167796==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167796==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167796==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167796== 
