==16061== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 7 of 7
==16061==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==16061==    by 0x17B45C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:114)
==16061==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:150)
==16061==    by 0x16ACA0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:153)
==16061==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:140)
==16061==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:398)
==16061==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==16061==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==16061==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==16061==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==16061==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==16061==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==16061== 
