
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
Teste nao vazio
-------------------------------------------------------------------------------
arvore.cpp:56
...............................................................................

arvore.cpp:60: FAILED:
  REQUIRE( a.vazio() == false )
with expansion:
  true == false

-------------------------------------------------------------------------------
Caso 1
-------------------------------------------------------------------------------
arvore.cpp:64
...............................................................................

arvore.cpp:71: FAILED:
  REQUIRE( saida == resultado )
with expansion:
  {  } == { 3, 7, 5 }

-------------------------------------------------------------------------------
Caso 3
-------------------------------------------------------------------------------
arvore.cpp:75
...............................................................................

arvore.cpp:82: FAILED:
  REQUIRE( saida == resultado )
with expansion:
  {  }
  ==
  { 'A', 'D', 'C', 'I', 'H', 'K', 'J', 'F' }

-------------------------------------------------------------------------------
Caso N
-------------------------------------------------------------------------------
arvore.cpp:86
...............................................................................

arvore.cpp:93: FAILED:
  REQUIRE( saida == resultado )
with expansion:
  {  }
  ==
  { 5, 28, 24, 45, 30, 60, 52, 98, 50 }

===============================================================================
test cases: 5 | 1 passed | 4 failed
assertions: 5 | 1 passed | 4 failed


ERRORS:
